[package]
name = "joshuaclarkelua/replica"
description = "Replication library heavily inspired by MadStudioRoblox/ReplicaService on github."
license = "MIT"
authors = ["Joshua Clarke (JCL)"]
version = "1.7.2"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Signal = "joshuaclarkelua/signal@^1.0"
Comm = "joshuaclarkelua/comm@^1.0"