[package]
name = "joshuaclarkelua/replica"
description = "Replication library heavily inspired by MadStudioRoblox/ReplicaService on github."
license = "MIT"
authors = ["JCL"]
version = "1.6.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Signal = "sleitnick/signal@1.2.1"
Trove = "sleitnick/trove@0.5.0"
Comm = "sleitnick/comm@0.3.1"
Fusion = "elttob/fusion@0.2.0"